version: 3

vars:
  PUBLIC_OPENAPI_YAML: openapi/public.openapi.yaml
  PUBLIC_API_OUT_DIR: publicapi

tasks:
  mod:download:
    run: once
    cmd: go mod download
    sources:
      - go.mod
      - go.sum

  codegen:
    run: once
    deps:
      - mod:download
    cmds:
      - rm -rf {{.PUBLIC_API_OUT_DIR}}
      - >-
        go tool oasmith
        --openapi {{.PUBLIC_OPENAPI_YAML}}
        --mode client
        --lang go
        --out {{.PUBLIC_API_OUT_DIR}}
    sources:
      - Taskfile.yaml
      - go.mod
      - go.sum
      - "{{.PUBLIC_OPENAPI_YAML}}"
    generates:
      - "{{.PUBLIC_API_OUT_DIR}}/**/*"

  test:
    run: once
    deps:
      - codegen
    cmd: go test -tags=dev ./...
    sources:
      - Taskfile.yaml
      - go.mod
      - go.sum
      - ./**/*.go
      - ./**/*.yaml

  lint:
    run: once
    deps:
      - codegen
    env:
      CGO_ENABLED: 0
    cmds:
      - gofmt -w .
      - >-
        go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.13.1
        run --allow-serial-runners --timeout=15m --build-tags=dev ./...
    sources:
      - Taskfile.yaml
      - go.mod
      - go.sum
      - .golangci.yaml
      - ./**/*.go
      - ./**/*.yaml

  build:
    run: once
    deps:
      - codegen
    cmd: go build ./...
    sources:
      - Taskfile.yaml
      - go.mod
      - go.sum
      - ./**/*.go
      - ./**/*.yaml

  check:
    run: once
    deps:
      - build
      - codegen
      - lint
      - test

  mod:tidy:
    deps:
      - codegen
    cmd: go mod tidy

  outdated:
    run: once
    cmd: >-
      go list -u -m
      -f '{{"{{"}}if and (not .Main) (not .Indirect) .Update{{"}}"}}{{"{{"}}.Path{{"}}"}} {{"{{"}}.Version{{"}}"}} => {{"{{"}}.Update.Version{{"}}"}}{{"{{"}}end{{"}}"}}'
      all
